language: rust
sudo: false
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"
cache: cargo

rust:

matrix:
  include:
  # This build uses stable and checks rustfmt and clippy.
  # We don't check them on nightly since their lints and formatting may differ.
  - rust: stable
    install:
      - rustup component add rustfmt
      - rustup component add clippy
    before_script:
      - cargo fmt -- --check
      - cargo clippy
  # Since many users will use nightlies, also test that.
  - rust: nightly

script:
  - cargo test --all -- --nocapture
